language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: __token__
#   password:
#     secure: qPqsVXTKeAtLnISO0Xg0LWhzNZPe5wUFDMnNcKfxIl8OYtxrEGUPsmr2XBiGtITDtTM8mytUPATTxV78t33Mp4woEJUmIAjV9H6oIXcydUX1BMbnJbOEl/5BnoZoiCFoG3SkqHfnausbByklU9KxvRNR6CfKSewL652jhBS/iDfXLCJFfpnO4aSZO3cYBA43GkpXDZKCns85HB2oK31lIrW/kWLxSmZdle87O1OT5a+V2vwgkkDWzl0/1CuxN5UYagOj08dbe7WoED8wJi9BjSkHR/ncyHdDsEHmqjQ5UDPasP7cgXjSxBO52w28t577aHRRpuzlVbI5WjuxgEz93i+dtPXx/pkUpDTVB9wScQwFlrIUy7Seud8JE6rTl4+cY3iot7sR2kltElp+/WSEHIjSQDJfm93Qy2ugrtczdWWW8uovb3lyVQ4Edmurq1s9P67GLKh5n5RitEeJnecgtBRcvx2hNEGEWnC3bu0Mqdv1ymT7U/3JCIwLvoVlKrNVmqhaVe4Y/1g2fXm8NKb8dnsXO2KLSh0zgadWDZ/KYa05nCEFEY1OzlOluwc1FF6BtYvqagVqhv1BHDNCoDE9CKHzHls9IPrb6ZRp4n+YJAKbMFSamk3QQQE/obrQmhwVxjIod/lkTsoawbLJ7+WiDuX7bmkmjajnizcgG5HIfqY=
#   skip_cleanup: true
#   skip_existing: true
#   on:
#     tags: true
#     repo: wjwillemse/solvency2-data
#     python: 3.7
