site_name: solvency2-data
site_url: https://wjwillemse.github.io/solvency2-data/
repo_url: https://github.com/wjwillemse/solvency2-data

theme: 
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections

plugins:
- search
- mkdocstrings

nav:
  - About: 'README.md'
  - Installation: 'installation.md'
  - Usage: 'usage.md'
  - Using a database: 'api_example.md'
  - Contributing: 'contributing.md'
  - History: 'history.md'
  - API documentation: 'api_docs.md'

use_directory_urls: false
